#!/usr/bin/env python3
"""Verify DOI metadata with Crossref and write a reproducible BibTeX file."""

from __future__ import annotations

import json
import re
import sys
import time
import unicodedata
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOI_FILE = ROOT / "docs" / "dois.txt"
OUTPUT = ROOT / "references.bib"
USER_AGENT = "SeqTecVerifier/2.0 (https://github.com/kevinkorfmann/seqtec)"


def request_json(url: str) -> dict:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=30) as response:
        return json.load(response)


def escape(value: str) -> str:
    return value.replace("&", r"\&").replace("%", r"\%").replace("#", r"\#")


def main() -> int:
    entries: list[str] = []
    failures: list[str] = []
    for raw in DOI_FILE.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        key, doi, expected = (part.strip() for part in line.split("|"))
        url = "https://api.crossref.org/works/" + urllib.parse.quote(doi, safe="")
        try:
            work = request_json(url)["message"]
        except (OSError, KeyError, json.JSONDecodeError) as exc:
            failures.append(f"{key}: could not retrieve {doi}: {exc}")
            continue

        authors = work.get("author", [])
        actual = authors[0].get("family", "") if authors else ""
        normalized = lambda value: re.sub(
            r"[^a-z]",
            "",
            unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode().lower(),
        )
        if normalized(actual) != normalized(expected):
            failures.append(f"{key}: expected {expected}, Crossref returned {actual or 'no author'}")
            continue

        displayed_authors = authors[:6]
        author_text = " and ".join(
            escape(" ".join(filter(None, [author.get("given"), author.get("family")])))
            for author in displayed_authors
        )
        if len(authors) > len(displayed_authors):
            author_text += " and others"
        title = escape(work.get("title", [""])[0])
        container = escape(work.get("container-title", [""])[0])
        date = work.get("published-print") or work.get("published-online") or work.get("issued", {})
        year = date.get("date-parts", [[""]])[0][0]
        entry_type = "article" if container else "misc"
        fields = [
            f"  author = {{{author_text}}}",
            f"  title = {{{{{title}}}}}",
            f"  year = {{{year}}}",
            f"  doi = {{{doi}}}",
        ]
        if container:
            fields.insert(2, f"  journaltitle = {{{container}}}")
        entries.append(f"@{entry_type}{{{key},\n" + ",\n".join(fields) + "\n}")
        print(f"VERIFIED {key}: {doi}")
        time.sleep(0.1)

    if failures:
        print("\n".join(failures), file=sys.stderr)
        return 1
    header = (
        "% Generated by scripts/verify_dois.py from docs/dois.txt.\n"
        "% Metadata and first-author surnames verified against Crossref.\n\n"
    )
    OUTPUT.write_text(header + "\n\n".join(entries) + "\n", encoding="utf-8")
    print(f"Wrote {len(entries)} verified references to {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
